### ISSUE TITLE
PHP Fatal error when fetching outbox

### ISSUE THREAD

**Issue by eroosenmaallen** [pfefferle/wordpress-activitypub#269]
When I try to remotely fetch the first page of my outbox, a PHP Fatal error occurs:
```
[02-Feb-2023 16:18:10 UTC] PHP Fatal error:  Uncaught TypeError: Activitypub\Model\Activity::from_post(): Argument #1 ($post) must be of type Activitypub\Model\Post, array given, called in /(path)/wordpress/wp-content/plugins/activitypub/includes/rest/class-outbox.php on line 106 and defined in /(path)/wordpress/wp-content/plugins/activitypub/includes/model/class-activity.php:48
Stack trace:
#0 /(path)/wordpress/wp-content/plugins/activitypub/includes/rest/class-outbox.php(106): Activitypub\Model\Activity->from_post(Array)
#1 /(path)/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1171): Activitypub\Rest\Outbox::user_outbox_get(Object(WP_REST_Request))
#2 /(path)/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/activitypub/1....', Array, NULL)
#3 /(path)/wordpress/wp-includes/rest-api/class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /(path)/wordpress/wp-includes/rest-api.php(410): WP_REST_Server->serve_request('/activitypub/1....')
#5 /(path)/wordpress/wp-includes/class-wp-hook.php(308): rest_api_loaded(Object(WP))
#6 /(path)/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /(path)/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#8 /(path)/wordpress/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#9 /(path)/wordpress/wp-includes/class-wp.php(780): WP->parse_request('')
#10 /(path)/wordpress/wp-includes/functions.php(1332): WP->main('')
#11 /(path)/wordpress/wp-blog-header.php(16): wp()
#12 /(path)/index.php(7): require('/homepages/6/d8...')
#13 {main}
  thrown in /(path)/wordpress/wp-content/plugins/activitypub/includes/model/class-activity.php on line 48
```
Individual posts are okay, as is the outbox OrderedCollection; the error seems to be limited to the OrderedCollectionPage.

**Comment by pfefferle** [comment]
I have already fixed it in this PR https://github.com/pfefferle/wordpress-activitypub/pull/265, but I think I will release a new version with that fix, asap. but it should not cause any big issues, because the outbox is not really used anywhere yet.

Thanks for reporting!
