### ISSUE TITLE
Uncaught Error: Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by alecmuffett** [pfefferle/wordpress-activitypub#314]
Version 0.17.0 logfiles

```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /path/wp-content/plugins/friends/feed-parsers/class-feed-parser-activitypub.php:484

Stack trace:

#0 /path/wp-includes/class-wp-hook.php(308): Friends\\Feed_Parser_ActivityPub->handle_received_activity(Array, 2, 'create')

#1 /path/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)

#2 /path/wp-includes/plugin.php(517): WP_Hook->do_action(Array)

#3 /path/wp-content/plugins/activitypub/includes/rest/class-inbox.php(149): do_action('activitypub_inb...', Array, 2, 'create')

#4 /path/wp-includes/rest-api/class-wp-rest-server.php(1171): Activitypub\\Rest\\Inbox::user_inbox_post(Object(WP_REST_Request))

#5 /path/wp-includes/rest-api/class-wp-rest-server.php(1018): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/activitypub/1....', Array, NULL)

#6 /path/wp-includes/rest-api/class-wp-rest-server.php(...

'
```

possibly related to another message:

```
AH01071: Got error 'PHP message: PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /path/wp-includes/http.php on line 687
```

**Comment by pfefferle** [comment]
This is an error in the friends plugin /cc @akirk

**Comment by akirk** [comment]
Sorry, it was already fixed in https://github.com/akirk/friends/commit/2e7f01e91c7d6ad4642dbe28a8bc2281e5c585f1 but I hadn't released a new version yet. I hope I can release it today.

**Comment by akirk** [comment]
I just released https://github.com/akirk/friends/releases/tag/2.5.3 which fixes this error.

**Comment by alecmuffett** [comment]
Much obliged!
